
###  <span style="color:#8E9092"><b>Incidental findings</b> (ACMG SF v2.0)</span>


```{r prepare_sf_data, echo=F, results='asis'}

tot_variants_p_clinvar <- NROW(cps_report[['content']][['snv_indel']][['variant_display']][['incidental']])

```

*  In the sample, a total of n = __`r tot_variants_p_clinvar`__ variants in [genes recommended for incidental findings reporting](https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/) 
are registered with a <i>Pathogenic/Likely pathogenic</i> clinical significance in ClinVar.

<br>

```{r sf_cancer, echo=F, results = 'asis', eval = tot_variants_p_clinvar > 0}

htmltools::br()
htmltools::br()

DT::datatable(cps_report[['content']][['snv_indel']][['variant_display']][['incidental']], escape=F,extensions=c("Buttons","Responsive"), 
              options = list(
                pageLength = 6,
                buttons = c('csv','excel'),
                dom = 'Bfrtip',
                initComplete = DT::JS(
                  "function(settings, json) {",
                  "$(this.api().table().header()).css({'background-color': '#8E9092', 'color': '#fff'});",
                  "}")
              )
)

htmltools::br()
htmltools::br()
```
