## Documentation

### Annotation resources

The analysis performed in the cancer genome report is based on the following underlying tools and knowledge resources:

* __Software__ 
```{r list_software, echo=F,results='asis'}
for(n in names(pcg_report$metadata$pcgr_db_release)){
  if(n == 'mosdepth'){
    next
  }
  if(pcg_report$metadata$pcgr_db_release[[n]]$resource_type == 'software'){
    s <- paste0('    * [',pcg_report$metadata$pcgr_db_release[[n]]$name,'](',pcg_report$metadata$pcgr_db_release[[n]]$url,') - ',pcg_report$metadata$pcgr_db_release[[n]]$description, ' (',pcg_report$metadata$pcgr_db_release[[n]]$version,')')
    cat(s,sep="\n")
  }
}

```
<br><br>

* __Databases/datasets__ 
```{r list_db, echo=F,results='asis'}
for(n in names(pcg_report$metadata$pcgr_db_release)){
  if(pcg_report$metadata$pcgr_db_release[[n]]$resource_type == 'db' & n != 'gwas' & n != 'ct'){
    s <- paste0('    * [',pcg_report$metadata$pcgr_db_release[[n]]$name,'](',pcg_report$metadata$pcgr_db_release[[n]]$url,') - ',pcg_report$metadata$pcgr_db_release[[n]]$description, ' (',pcg_report$metadata$pcgr_db_release[[n]]$version,')')
    cat(s,sep="\n")
  }
}

```

