## Report & query settings

```{r on_off_settings, echo=F}
signatures_estimation <- 'ON'
msi_prediction <- 'ON'
mutational_burden <- 'ON'
if(pcg_report$content$msi$eval == F){
  msi_prediction <- 'OFF'
}
if(pcg_report$content$m_signature$eval == F){
  signatures_estimation <- 'OFF'
}
if(pcg_report$content$tmb$eval == F){
  mutational_burden <- 'OFF'
}
```

The report is generated with _[PCGR](https://github.com/sigven/pcgr)_ version `r pcg_report[['metadata']][['pcgr_version']]`, using the following key settings:

* Genome assembly: __`r pcg_report[['metadata']][['genome_assembly']]`__
* Tumor type:  __`r pcg_report[['metadata']][['tumor_class']]`__
* Sequencing mode input (VCF): __`r pcg_report[['content']][['sequencing_mode']][['mode']]`__
* Coding target size (VCF): __`r pcg_report[['metadata']][['config']][['mutational_burden']][['target_size_mb']]` Mb__
* Minimum sequencing depth (DP) tumor (SNV + InDels): __`r pcg_report[['metadata']][['config']][['allelic_support']][['tumor_dp_min']]`__
* Minimum allelic fraction (AF) tumor (SNV + InDels): __`r pcg_report[['metadata']][['config']][['allelic_support']][['tumor_af_min']]`__
* Minimum sequencing depth (DP) control (SNV + InDels): __`r pcg_report[['metadata']][['config']][['allelic_support']][['control_dp_min']]`__
* Maximum allelic fraction (AF) control (SNV + InDels): __`r pcg_report[['metadata']][['config']][['allelic_support']][['control_af_max']]`__
* Tier system (VCF): __`r pcg_report[['metadata']][['config']][['tier_model']][['tier_model']]`__
* MSI prediction: __`r msi_prediction`__
* Mutational burden estimation: __`r mutational_burden`__
* Mutational signatures estimation: __`r signatures_estimation`__
* Report theme (Bootstrap): __`r pcg_report[['metadata']][['config']][['visual']][['report_theme']]`__


