---
title: "Cancer genome sequencing report for precision oncology - `r pcg_report$sample_name`"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
bibliography: bibliography.bib
nocite: |
  @Rosenthal2016-cn, @Kim2016-od, @Alexandrov2013-uh, @Alexandrov2013-gs, @Dong2016-sb, @Secrier2016-qo, @Cortes-Ciriano2017-vl
output: 
  html_document:
    toc: true
    theme: default
    number_sections: false
    toc_float: true
    toc_depth: 3
    fig_width: 5
    fig_height: 4
    includes:
      after_body: disclaimer.md
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = F,warning=FALSE, dpi=72, error=F, eval=T)
```

```{r settings_data_sources, child='settings_data_sources.Rmd'}
```

```{r conditional_seq_mode, child='value_boxes.Rmd', eval = pcg_report[['value_box']][['eval']]}
```

```{r conditional_seq_mode, child='snv_indel_header.Rmd', eval = pcg_report[['sequencing_mode']][['eval']]}
```

```{r conditional_seq_mode, child='snv_indel_zero.Rmd', eval = pcg_report[['snv_indel']][['zero']]}
```

```{r conditional_tumor_only, child='tumor_only_statistics.Rmd', eval = pcg_report[['tumor_only']][['eval']]}
```

```{r conditional_mutational_burden, child='mutational_burden.Rmd', eval = pcg_report[['tmb']][['eval']]}
```

```{r conditional_var_stats, child='variant_statistics_browser.Rmd', eval = pcg_report[['snv_indel']][['eval']]}
```

```{r conditional_tier1, child='tier1.Rmd', eval = pcg_report[['snv_indel']][['eval']]}
```

```{r conditional_tier2, child='tier2.Rmd', eval = pcg_report[['snv_indel']][['eval']]}
```

```{r conditional_tier3, child='tier3.Rmd', eval = pcg_report[['snv_indel']][['eval']]}
```

```{r conditional_tier4, child='tier4.Rmd', eval = pcg_report[['snv_indel']][['eval']]}
```

```{r conditional_tier_noncoding, child='tier_noncoding.Rmd', eval = pcg_report[['pcgr_config']][['other']][['list_noncoding']]}
```

```{r conditional_cna_overview, child='cna_report_segments_nondiploid.Rmd', eval = pcg_report[['cna']][['eval']]}
```

```{r conditional_cna_oncogene, child='cna_report_oncogene_gain.Rmd', eval = pcg_report[['cna']][['eval']]}
```

```{r conditional_cna_tsgene, child='cna_report_tsgene_loss.Rmd', eval = pcg_report[['cna']][['eval']]}
```

```{r conditional_cna_biomarker, child='cna_report_biomarkers.Rmd', eval = pcg_report[['cna']][['eval']]}
```

```{r conditional_msi, child='msi.Rmd', eval = pcg_report[['msi']][['eval']]}
```

```{r conditional_msi_missing, child='msi_missing.Rmd', eval = pcg_report[['msi']][['missing_data']]}
```

```{r conditional_msig, child='mutational_signature.Rmd', eval = pcg_report[['m_signature']][['eval']]}
```

```{r conditional_msig_missing, child='msig_missing.Rmd', eval = pcg_report[['m_signature']][['missing_data']]}
```

## References

