---
title: "Allelic fraction/depth test - for Oliver H"
author: "Sigve Nakken"
date: "2/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ad_test, echo=F, results = 'asis'}
library(crosstalk)

var_df <- data.frame('depth_tumor' = ceiling(runif(300,1,1000)), 'af_tumor' = round(runif(300,0,1), digits=2), 'depth_control' = ceiling(runif(300,1,1000)), 'af_control' = round(runif(300,0,0.1), digits=2))

var_df$coverage_tumor <- NA
var_df[var_df$depth_tumor < 20,]$coverage_tumor <- 'lowCoverage'
var_df[var_df$depth_tumor >= 20 & var_df$depth_tumor < 50,]$coverage_tumor <- '20-50X'
var_df[var_df$depth_tumor >= 50 & var_df$depth_tumor < 100,]$coverage_tumor <- '50-100X'
var_df[var_df$depth_tumor >= 100 & var_df$depth_tumor < 200,]$coverage_tumor <- '100-200X'
var_df[var_df$depth_tumor >= 200 & var_df$depth_tumor < 500,]$coverage_tumor <- '200-500X'
var_df[var_df$depth_tumor >= 500,]$coverage_tumor <- '500X'
var_df$coverage_control <- NA
var_df[var_df$depth_control < 20,]$coverage_control <- 'lowCoverage'
var_df[var_df$depth_control >= 20 & var_df$depth_control < 50,]$coverage_control <- '20-50X'
var_df[var_df$depth_control >= 50 & var_df$depth_control < 100,]$coverage_control <- '50-100X'
var_df[var_df$depth_control >= 100 & var_df$depth_control < 200,]$coverage_control <- '100-200X'
var_df[var_df$depth_control >= 200 & var_df$depth_control < 500,]$coverage_control <- '200-500X'
var_df[var_df$depth_control >= 500,]$coverage_control <- '500X'

variants_shared <- crosstalk::SharedData$new(var_df)
crosstalk::bscols(
  list(
    crosstalk::filter_slider("depth_tumor", "Sequencing depth tumor", variants_shared, ~depth_tumor, sep=F, ticks = T, step=100, dragRange = F),
    crosstalk::filter_slider_allelic_fraction("af_tumor", "Allelic fraction tumor", variants_shared, ~af_tumor, sep=F, ticks = T, step=0.05, dragRange = F),
    crosstalk::filter_select("coverage_tumor", "Coverage class - tumor", variants_shared, ~coverage_tumor)
  ),
  list(
    crosstalk::filter_slider("depth_control", "Sequencing depth control", variants_shared, ~depth_control, sep=F, ticks = T, step=100, dragRange = F),
    crosstalk::filter_slider("af_control", "Allelic fraction control", variants_shared, ~af_control, sep=F, ticks = T, dragRange = F),
    crosstalk::filter_select("coverage_control", "Coverage class - control", variants_shared, ~coverage_control)
  )
)

htmltools::br()
htmltools::br()

crosstalk::bscols(
  DT::datatable(variants_shared, escape=F,extensions=c("Buttons","Responsive"), width = "100%",options=list(buttons = c('csv','excel'),dom = 'Bfrtip'))
)
```

