package:
  name: dgg-rules-somatic
  version: 0.1.0

source:
  path: ../../..

build:
  number: 0
  noarch: python

requirements:
  build:
    - curl
    - unzip
    - tar
    - python
  run:
    - python
    - pandas
    - scipy
    - numpy
    - pip
    - pybedtools
    - cyvcf2
    - pyyaml

test:
  commands:
    - dgg-rules-somatic --version

about:
  home: https://github.com/LauferVA/dgg_rules_somatic
  license: MIT
  summary: DGG Variant Interpretation Engine - automated classification of genomic variants for clinical reporting.
