---
title: "Cancer Genome Report by PCGR"
bibliography: bibliography.bib
nocite: |
  @Tamborero2018-aj, @Poti2019-qr, @Alexandrov2020-gj, 
  @Alexandrov2013-gs, @Griffith2017-do, @Ma2018-to, 
  @Cortes-Ciriano2017-vl, @Li2017-ew,
  @Blokzijl2018-nc, @Lever2019-xp, @Repana2019-dd, 
  @Chalmers2017-cz, @Yin2020-or, @Bailey2018-os, @Fernandez2019-mk
format: 
  dashboard:
    nav-buttons: 
      - github
    github: https://github.com/sigven/pcgr
    orientation: rows
    theme: 
      - cosmo
      - pcgrr.scss
#css: pcgr_flexdb_tumor_control.css
---

```{r setup}
#| include: FALSE

signatures_estimation <- 'ON'
msi_prediction <- 'ON'
mutational_burden <- 'ON'
trial_inclusion <- 'ON'
# if(pcg_report[['content']][['msi']][['eval']] == F){
#   msi_prediction <- 'OFF'
# }
# if(pcg_report[['content']][['mutational_signatures']][['eval']] == F){
#   signatures_estimation <- 'OFF'
# }
# if(pcg_report[['content']][['tmb']][['eval']] == F){
#   mutational_burden <- 'OFF'
# }
# if(pcg_report[['content']][['clinicaltrials']][['eval']] == F){
#   trial_inclusion <- 'OFF'
# }
spam <- 8
#options(DT.options = list(scrollY="100vh", scrollCollapse = T))

#scrollY_flexdb_container <- "510px"
```
<style>
.datatables{
    overflow: auto;
}
.chart-stage-flex {
  overflow: scroll !important;
}
.value-box .value {
    color: white;
}
.value-box .caption {
    color: white;
}
</style>

# Menu 1

## Row

```{r summary_cpsr_findings}
#| output: asis
#| echo: false
#| eval: true

bslib::layout_column_wrap(
  width = 1/5,
  height = 120,
  bslib::value_box(
    title = "",
    value = "SNVs/InDels",
    showcase = NULL, 
    theme = bslib::value_box_theme(
      bg = "black", fg = "#fff")
  ),
  bslib::value_box(
    title = "Pathogenic/likely pathogenic variants",
    value = "N = 16",
    showcase = bsicons::bs_icon("bullseye"), 
    theme = bslib::value_box_theme(
      bg = "black", fg = "#fff")
  ),
  bslib::value_box(
    title = "Cancer predisposition genes affected",
    value = "BRCA1",
    showcase = bsicons::bs_icon("bullseye"),
    theme = bslib::value_box_theme(
      bg = "black", fg = "#fff")
  ),
  bslib::value_box(
    title = "Secondary findings",
    value = "1",
    showcase = bsicons::bs_icon("bullseye"),
    theme = bslib::value_box_theme(
      bg = "black", fg = "#fff")
  ),
  bslib::value_box(
    title = "GWAS findings",
    value = "1",
    showcase = bsicons::bs_icon("bullseye"),
    theme = bslib::value_box_theme(
      bg = "black", fg = "#fff")
  )
)
```

## Row {height="80%"}

### Biomarker variants

```{r}
#| title: Biomarker variants

DT::datatable(mtcars)
```

### Biomarker variants2



```{r}
#| title: Biomarker variants

DT::datatable(mtcars)
```


# Menu 2

:::: {.columns}

::: {.column width="70%"}
I would like to have text here

Sentence becomes longer, it should automatically stay in their column
:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="20%"}
and here

More text
:::

::::

# Menu 3
