---
title: "Cancer Predisposition Genome Report by CPSR"
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
bibliography: bibliography.bib
nocite: |
  @Huang2018-ah, @Richards2015-kj, @Maxwell2016-mr, @Amendola2016-pu, @Griffith2017-do, @Martin2019-nq, @Nykamp2017-rj
output: 
  html_document:
    theme: default
    toc: true
    toc_depth: 1
    number_sections: false
    toc_float:
      collapsed: false
      smooth_scroll: true
    fig_width: 5
    fig_height: 4
    includes:
      after_body: disclaimer_predisposition.md
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = F,warning=FALSE, dpi=72, error=F, eval=T)
options(scipen=999)

# width_panel <- 14
# height_panel <- 3 + as.integer((max(0,(NROW(cps_report[['metadata']][['gene_panel']][['genes']]) - 24)) / 16))

width_donut <- 10
height_donut <- 7

set_all <- NROW(cps_report$content$snv_indel$variant_set$tsv)


set_clinvar <- 0
set_other <- 0
if(cps_report$content$snv_indel$eval == T){
  if(cps_report$content$snv_indel$v_stat$n > 0){
    set_clinvar <- NROW(cps_report$content$snv_indel$variant_set$tsv %>% dplyr::filter(!is.na(CLINVAR_CLASSIFICATION)))
    set_other <- NROW(cps_report$content$snv_indel$variant_set$tsv %>% dplyr::filter(is.na(CLINVAR_CLASSIFICATION) & !is.na(CPSR_CLASSIFICATION) > 0))
  }
}

if(set_other == 0 | set_clinvar == 0){
  width_donut <- 6
  height_donut <- 4
}

```

```{r settings_cpsr, child='cpsr_rmarkdown/cpsr_settings.Rmd'}
```


```{r panel_cpsr, child='cpsr_rmarkdown/cpsr_virtual_panel.Rmd'}
```

```{r summary_cpsr, child='cpsr_rmarkdown/cpsr_summary.Rmd'}
```

```{r no_variants, eval = !cps_report[['content']][['snv_indel']][['eval']], results = "asis"}
cat('<br><ul>')
cat("<li><b>NO</b> variants found in the selected virtual gene panel/custom geneset</li>")
cat('</ul><br>')
```


```{r conditional_class_1_5, child='cpsr_rmarkdown/cpsr_tiers.Rmd', eval = cps_report[['content']][['snv_indel']][['eval']]}
```

<br><br>

```{r conditional_biomarkers, child='cpsr_rmarkdown/cpsr_biomarkers.Rmd', eval = cps_report[['content']][['snv_indel']][['eval']]}
```

<br><br>

```{r conditional_secondary, child='cpsr_rmarkdown/cpsr_secondary_findings.Rmd', eval = cps_report[['metadata']][['config']][['secondary_findings']]}
```

```{r global_options2, include=FALSE}
options(scipen=0)
```

```{r conditional_gwas, child='cpsr_rmarkdown/cpsr_gwas.Rmd', eval = cps_report[['metadata']][['config']][['gwas_findings']]}
```

```{r conditional_documentation, child='cpsr_rmarkdown/cpsr_documentation.Rmd', eval = TRUE}
```

<br><br>

## References

