sCNA tsgene {.hidden}
===================================== 

Row
-------------------------------------

### Key findings


```{r cna_vbox_mainhits1}
flexdashboard::valueBox("sCNA", caption = NULL, color = "#000000", icon = NULL)
```

### Proto-oncogenes subject to amplification

```{r cna_gains_oncogenes1, echo = F}
flexdashboard::valueBox(NROW(pcg_report$content$cna$disp$oncogene_gain),
                        color = ifelse(NROW(pcg_report$content$cna$disp$oncogene_gain) > 0,
                                       pcg_report$metadata$color_value_box,
                                       pcg_report$metadata$color_none),
                        icon = "fa-dna", href="#scna-oncogene")
```

### Loss of tumor suppressor genes

```{r cna_loss_tsgene1, echo = F}
flexdashboard::valueBox(NROW(pcg_report$content$cna$disp$tsgene_loss),
                        color = ifelse(NROW(pcg_report$content$cna$disp$tsgene_loss) > 0,
                                       pcg_report$metadata$color_value_box,
                                       pcg_report$metadata$color_none),
                        icon = "fa-dna", href="#scna-tsgene")
```

### Other drug targets subject to amplification

```{r cna_gain_target1, echo = F}
flexdashboard::valueBox(NROW(pcg_report$content$cna$disp$other_target),
                        color = ifelse(NROW(pcg_report$content$cna$disp$other_target) > 0,
                                       pcg_report$metadata$color_value_box,
                                       pcg_report$metadata$color_none),
                        icon = "fa-dna", href="#scna-other")
```

Row
-----------------------------------------------------

### Loss of tumor suppressor genes - filters {data-padding=15 data-width=300}

<br><br>

```{r table_browse_scna_tsgene, echo=F, results = "asis", eval = NROW(pcg_report$content$cna$disp$tsgene_loss) > 0}

cat('\nTumor suppressor genes subject to homozygous deletions (right panel) can be filtered according to various criteria:\n')

tsgene_loss_variants <- crosstalk::SharedData$new(pcg_report[["content"]][["cna"]][["disp"]][["tsgene_loss"]])
crosstalk::bscols(
  list(
    crosstalk::filter_select("SYMBOL", "Gene", tsgene_loss_variants, ~SYMBOL),
    crosstalk::filter_slider("LOG_R", "Log-ratio", tsgene_loss_variants, ~LOG_R)
  ),
  list(
    crosstalk::filter_select("CHROMOSOME", "Chromosome", tsgene_loss_variants, ~CHROMOSOME),
    crosstalk::filter_select("EVENT_TYPE", "CNA event", tsgene_loss_variants, ~EVENT_TYPE)
  )
)

```


```{r tsgene_missing_filters, echo=F, results = 'asis', eval = NROW(pcg_report$content$cna$disp$tsgene_loss) == 0}
cat('\n*  <i> <b>No</b> tumor suppressor genes subject to homozygous deletions.</i>',sep='\n')
cat('\n')
```


### Loss of tumor suppressor genes {data-padding=15}

<br><br>

```{r table_scna_tsgene, eval = NROW(pcg_report$content$cna$disp$tsgene_loss) > 0}

tsgene_loss_variants %>%
  DT::datatable(escape = F, 
                extensions = c("Buttons","Responsive"), 
                options = list(pageLength = 8, 
                               scrollY = scrollY_flexdb_container, 
                               buttons = c('csv','excel'), 
                               autoWidth = T, 
                 fixedColumns = T,
                 fixedHeader = T,
                 #scrollX = F,
                  columnDefs = list(list(width = '90px', targets = c(1,2,3,4,5,6))),
                               dom = 'Bfrtip'))

```


```{r tsgene_missing_data, echo=F, results = 'asis', eval = NROW(pcg_report$content$cna$disp$tsgene_loss) == 0}
cat('\n*  <i> <b>No</b> tumor suppressor genes subject to homozygous deletions.</i>',sep='\n')
cat('\n')
```

