
###  <span style="color:#8E9092"><b>Secondary findings</b> (ACMG SF v2.0)</span>


```{r prepare_sf_data, echo=F, results='asis'}

tot_variants_p_clinvar <- NROW(cps_report[['content']][['snv_indel']][['variant_display']][['sf']])

```

*  A total of n = __`r tot_variants_p_clinvar`__ variants in [genes recommended for incidental findings reporting](https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/) are registered with a <i>Pathogenic/Likely pathogenic</i> clinical significance in ClinVar.

<br>

```{r sf_cancer, echo=F, results = 'asis', eval = T}
library(summarywidget)
library(crosstalk)

htmltools::br()
htmltools::br()

crosstalk::bscols(
  DT::datatable(cps_report[['content']][['snv_indel']][['variant_display']][['sf']], escape=F,extensions=c("Buttons","Responsive"), width = "100%",
                options = list(
                  buttons = c('csv','excel'),
                  dom = 'Bfrtip',
                  initComplete = DT::JS(
                      "function(settings, json) {",
                      "$(this.api().table().header()).css({'background-color': '#8E9092', 'color': '#fff'});",
                      "}")
                  )
                )
)

#htmltools::br()

```
