package:
  name: r-pcgrr
  version: 2.2.1 # versioned by bump2version

source:
  path: ../../../pcgrr

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git
  host:
    - r-base ==4.3.3
    - r-assertable
    - r-assertthat
    - bioconductor-biostrings
    - r-bslib
    - r-caret
    - r-crosstalk
    - r-dplyr
    - r-dt
    - r-formattable
    - bioconductor-genomeinfodb
    - r-ggplot2
    - r-glue
    - r-htmltools
    - r-log4r
    - bioconductor-mutationalpatterns
    - r-openxlsx2
    - r-plotly
    - bioconductor-quantiseqr
    - r-quarto
    - quarto
    - r-randomforest
    - r-readr
    - r-reshape2
    - r-rlang
    - r-rrapply
    - bioconductor-s4vectors
    - r-scales
    - r-shiny
    - r-stringr
    - r-stringi
    - r-tidyr
    - r-yaml

  run:
    - r-base ==4.3.3
    - r-assertable
    - r-assertthat
    - bioconductor-biostrings
    - r-bslib
    - r-caret
    - r-crosstalk
    - r-dplyr
    - r-dt
    - r-formattable
    - bioconductor-genomeinfodb
    - r-ggplot2
    - r-glue
    - r-htmltools
    - r-log4r
    - bioconductor-mutationalpatterns
    - r-openxlsx2
    - r-plotly
    - bioconductor-quantiseqr
    - r-quarto
    - quarto
    - r-randomforest
    - r-readr
    - r-reshape2
    - r-rlang
    - r-rrapply
    - bioconductor-s4vectors
    - r-scales
    - r-shiny
    - r-stringr
    - r-stringi
    - r-tidyr
    - r-yaml

test:
  commands:
    - $R -e "library('pcgrr')"

about:
  home: https://github.com/sigven/pcgr/pcgrr
  license: MIT
  summary: Personal Cancer Genome ReporteR.
    Functions, tools and utilities for the generation of clinical
    cancer genome reports with PCGR. This R package is an integrated
    part of the Docker/Conda-based PCGR workflow (https://github.com/sigven/pcgr),
    it should thus not be used as a stand-alone package.
