
sCNA oncogene {.hidden}
===================================== 

Row
-------------------------------------

### Key findings


```{r cna_vbox_mainhits}
flexdashboard::valueBox("sCNA", caption = NULL, color = "#000000", icon = NULL)
```

### Proto-oncogenes subject to amplification

```{r cna_gains_oncogenes, echo = F}
flexdashboard::valueBox(NROW(pcg_report$content$cna$disp$oncogene_gain),
                        color = ifelse(NROW(pcg_report$content$cna$disp$oncogene_gain) > 0,
                                       pcg_report$metadata$color_value_box,
                                       pcg_report$metadata$color_none),
                        icon = "fa-dna", href="#scna-oncogene")
```

### Loss of tumor suppressor genes

```{r cna_loss_tsgene, echo = F}
flexdashboard::valueBox(NROW(pcg_report$content$cna$disp$tsgene_loss),
                        color = ifelse(NROW(pcg_report$content$cna$disp$tsgene_loss) > 0,
                                       pcg_report$metadata$color_value_box,
                                       pcg_report$metadata$color_none),
                        icon = "fa-dna", href="#scna-tsgene")
```

### Other drug targets subject to amplification

```{r cna_gain_target, echo = F}
flexdashboard::valueBox(NROW(pcg_report$content$cna$disp$other_target),
                        color = ifelse(NROW(pcg_report$content$cna$disp$other_target) > 0,
                                       pcg_report$metadata$color_value_box,
                                       pcg_report$metadata$color_none),
                        icon = "fa-dna", href="#scna-other")
```

Row
-----------------------------------------------------

### Gain of proto-oncogenes - filters {data-padding=15 data-width=300}


<br><br>

```{r table_browse_scna_oncogene, echo=F, results = "asis", eval = NROW(pcg_report$content$cna$disp$oncogene_gain) > 0}

cat('\nProto-oncogenes subject to amplifications (right panel) can be filtered according to various criteria:\n')

drug_levels <- levels(as.factor(pcg_report[["content"]][["cna"]][["disp"]][["oncogene_gain"]]$DRUGS_ON_LABEL))
# if(length(drug_levels) > 0){
#   tier3_vars <- tier3_vars |>
#     dplyr::arrange(MUTATION_HOTSPOT, desc(OPENTARGETS_RANK))
# }

oncogene_gain_variants <- crosstalk::SharedData$new(pcg_report[["content"]][["cna"]][["disp"]][["oncogene_gain"]])
crosstalk::bscols(
  list(
    crosstalk::filter_select("SYMBOL", "Gene", oncogene_gain_variants, ~SYMBOL),
    crosstalk::filter_slider("LOG_R", "Log-ratio", oncogene_gain_variants, ~LOG_R)
  ),
  list(
    crosstalk::filter_select("CHROMOSOME", "Chromosome", oncogene_gain_variants, ~CHROMOSOME),
    crosstalk::filter_select("EVENT_TYPE", "CNA event", oncogene_gain_variants, ~EVENT_TYPE)
  )
)

```


```{r oncogene_missing_filters, echo=F, results = 'asis', eval = NROW(pcg_report$content$cna$disp$oncogene_gain) == 0}
cat('\n*  <i> <b>No</b> proto-oncogenes subject to copy number amplifications.</i>',sep='\n')
cat('\n')
```


### Gain of proto-oncogenes {data-padding=15}

<br><br>

```{r table_scna_oncogene, eval = NROW(pcg_report$content$cna$disp$oncogene_gain) > 0}

dt <- oncogene_gain_variants |>
  DT::datatable(escape = F, 
                extensions = c("Buttons","Responsive"), 
                options = list(
                  pageLength = 8, 
                  scrollY = scrollY_flexdb_container, 
                  buttons = c('csv','excel'), 
                  #autoWidth = T, 
                  #fixedColumns = T,
                  #fixedHeader = T,
                  scrollX = "900px",
                  #columnDefs = list(list(width = '90px', targets = c(1,2,3,4,5,6))),
                  dom = 'Bfrtip'))

if(length(drug_levels) > 0){
  dt <- dt |>
    DT::formatStyle("DRUGS_ON_LABEL","DRUGS_ON_LABEL",
                    color = "white", fontWeight = "bold",
                    backgroundColor = DT::styleEqual(drug_levels, rep("black", length(drug_levels)))
    )
}
dt |>
  DT::formatStyle("SYMBOL","OPENTARGETS_RANK", color = "white", backgroundColor = DT::styleInterval(pcg_report[['content']][['report_display_config']][['opentargets_rank']][['breaks']], pcg_report[['content']][['report_display_config']][['opentargets_rank']][['colors']]))

```


```{r oncogene_missing_data, echo=F, results = 'asis', eval = NROW(pcg_report$content$cna$disp$oncogene_gain) == 0}
cat('\n*  <i> <b>No</b> proto-oncogenes subject to copy number amplifications.</i>',sep='\n')
cat('\n')
```

