Mutational signatures
==================================================================


```{r check_analysis_status, echo = F}
missing_data_norun <- F
if(pcg_report$content$m_signature_mp$eval == F | pcg_report$content$m_signature_mp$missing_data == T){
  missing_data_norun <- T
}
```


Row
-------------------------------------

### Mutational Signatures (SBS)

```{r mugsig_overview_box}
flexdashboard::valueBox("SIGNATURES", caption = NULL, color = '#000000', icon = NULL)
```

### SNVs eligible for analysis

```{r mutsig_snv_box}
col <- pcg_report$metadata$color_value_box
if(pcg_report$content$snv_indel$v_stat$n_snv < 100){
  col <- pcg_report[['metadata']][['color_palette']][['warning']][['values']][1]
}
flexdashboard::valueBox(pcg_report$content$snv_indel$v_stat$n_snv, color = col, icon = "fa-dna")
```


### Most dominant aetiology

```{r mutsig_dominant_box}
if(!missing_data_norun){
  m <- pcg_report$content$m_signature_mp$result$contributions$per_group |> 
    dplyr::arrange(desc(prop_group))
  flexdashboard::valueBox(m$group[1], color = pcg_report$metadata$color_value_box)
}else{
  flexdashboard::valueBox("ND", color = pcg_report$metadata$color_none)

}
```


### Accuracy of signature fitting (%)

```{r mutsig_accuracy_box}
if(!missing_data_norun){
  cosine_sim <- pcg_report$content$m_signature_mp$result$goodness_of_fit
  flexdashboard::valueBox(cosine_sim, color = ifelse(cosine_sim > 90,
                          pcg_report[['metadata']][['color_palette']][['success']][['values']][1],
                          pcg_report[['metadata']][['color_palette']][['warning']][['values']][1]))
}else{
  flexdashboard::valueBox("ND", color = pcg_report$metadata$color_none)
}
```

### High confident kataegis events

```{r mutsig_kataegis_box}
num_events <- NROW(pcg_report$content$kataegis$events)
if(num_events > 0){
  num_events <- NROW(pcg_report$content$kataegis$events |> dplyr::filter(confidence == 3))
}
flexdashboard::valueBox(num_events, color = ifelse(num_events > 0,
                        pcg_report[['metadata']][['color_palette']][['success']][['values']][1],
                        pcg_report$metadata$color_none))
```


Row {data-height=580}
-------------------------------------

### Mutational signatures - aetiology contributions {data-width=270, data-padding=10}
    
```{r mutsigs_donut, eval = !missing_data_norun}

plot_data <- 
  pcg_report$content$m_signature_mp$result$contributions$per_group
scale_fill <- 
  pcg_report$content$m_signature_mp$result$scale_fill_values
names(scale_fill) <- pcg_report$content$m_signature_mp$result$scale_fill_names


ggplot2::ggplot(plot_data, ggplot2::aes(x = 2, y = prop_group, fill = group)) +
     ggplot2::geom_bar(width = 1, stat = "identity", color = "white") +
     ggplot2::coord_polar(theta = "y", start = 0) +
     ggplot2::scale_fill_manual(values = scale_fill) +
     ggplot2::theme_void() + 
     ggplot2::xlim(.5, 2.5) +
     ggplot2::theme(legend.position = "right",
                    legend.title = ggplot2::element_blank(),
                    plot.margin = ggplot2::margin(0.5, 0.5, 0.5, 0.5, "cm"),
                    legend.text = ggplot2::element_text(family = "Helvetica", size = 14))



```


```{r mutsigs_missing_contributions, echo = F, eval = missing_data_norun, results = 'asis'}
htmltools::br()

cat('\n')

cat(paste0('-   <b>NOT DETERMINED (ND)</b>: The number of SNV calls (n = ',nrow(pcg_report[['content']][['m_signature_mp']][['variant_set']][['all']]),') is too limited. A minimum of ',pcg_report[['metadata']][['config']][['msigs']][['mutation_limit']],' SNVs is currently required for a mutational signature analysis to be performed.'), sep ="\n")

```



### Mutational signatures - aetiologies {data-padding=10}
    
```{r mutsigs_aetiologies, echo = F, eval = !missing_data_norun}

signature_ids <- pcg_report[['content']][['m_signature_mp']][['result']][['contributions']][['per_signature']]$signature_id
signature_colors <- pcg_report[['content']][['m_signature_mp']][['result']][['contributions']][['per_signature']]$col

myOptions <- list(buttons = c('csv','excel'),
                  dom = 'Bfrtip', 
                  #autoWidth = T, 
                  fixedColumns = T,
                  columnDefs = list(list(width = '10%', targets = c(1,2)),
                                    list(width = '40%', targets = 5),
                                    list(width = '20%', targets = c(3,4))),
                  # columnDefs = list(list(width = '70px', targets = c(1,2)),
                  #                   list(width = '220px', targets = c(3,4))),
                  scrollCollapse = T)
dat <- dplyr::select(pcg_report$content$m_signature_mp$result$contributions$per_signature, -c(sample_id,col,prop_signature)) |>
  dplyr::select(signature_id, contribution, group, dplyr::everything())
DT::datatable(dat ,options = myOptions, extensions=c("Buttons")) |>
 DT::formatStyle('contribution',fontWeight = 'bold') |>
 DT::formatStyle('signature_id',color = 'white', 
                 backgroundColor = DT::styleEqual(signature_ids, signature_colors), 
                 fontWeight = 'bold', `text-align` = 'center')

``` 

```{r mutsigs_missing_aetiologies, echo = F, eval = missing_data_norun, results = "asis"}
htmltools::br()

cat('\n')

cat(paste0('-   <b>NOT DETERMINED (ND)</b>: The number of SNV calls (n = ',nrow(pcg_report[['content']][['m_signature_mp']][['variant_set']][['all']]),') is too limited. A minimum of ',pcg_report[['metadata']][['config']][['msigs']][['mutation_limit']],' SNVs is currently required for a mutational signature analysis to be performed.'), sep ="\n")


```


Row {.tabset .tabset-fade}
--------------------------------------------
   
### Mutational context frequency 

```{r mutsigs_context_frequency, fig.width = 20, fig.height = 3, eval = !missing_data_norun}
## frequency of mutation contexts (96)
MutationalPatterns::plot_96_profile(pcg_report$content$m_signature_mp$result$mut_mat, 
                                    colors = RColorBrewer::brewer.pal(6, "Dark2"), ymax = 0.3)
```   
 
```{r missing_context_frequency, eval = missing_data_norun, results = "asis"}
htmltools::br()

cat('\n')

cat(paste0('-   <b>NOT DETERMINED (ND)</b>: The number of SNV calls (n = ',nrow(pcg_report[['content']][['m_signature_mp']][['variant_set']][['all']]),') is too limited. A minimum of ',pcg_report[['metadata']][['config']][['msigs']][['mutation_limit']],' SNVs is currently required for a mutational signature analysis to be performed.'), sep ="\n")



```   
 
 
### Genomic distribution - rainfall
    
```{r mutsigs_rainfall, fig.width = 20, fig.height = 3, eval = pcg_report$content$rainfall$eval & NROW(pcg_report$content$rainfall$rfdata$data) > 0}

## retrieve rainfall data
rfdat <- pcg_report$content$rainfall$rfdata

## set size of text and points in plot
cex <- 0.8
cex_text <- 3

# make rainfall plot with rfdat
plot <- ggplot2::ggplot(rfdat$data, ggplot2::aes(x = location, y = distance)) +
    ggplot2::geom_point(ggplot2::aes(colour = factor(type)), cex = rfdat$cex) +
    ggplot2::geom_vline(xintercept = as.vector(rfdat$chr_cum), linetype="dotted") +
    ggplot2::annotate("text", x = rfdat$intercept, 
                      y = rfdat$ylim, 
                      label = rfdat$labels, 
                      cex = rfdat$cex_text) +
    ggplot2::xlab("Genomic Location") +
    ggplot2::ylab("Genomic Distance") +
    ggplot2::scale_y_log10() +
    ggplot2::scale_colour_manual(values = rfdat$colors) +
    ggplot2::scale_x_continuous(expand = c(0,0), limits=c(0, max(rfdat$chr_cum))) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = "bottom",
      legend.title = ggplot2::element_blank(),
      legend.key = ggplot2::element_blank(),
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank()) +
    ggplot2::guides(colour = ggplot2::guide_legend(nrow = 1))

plot <- plot |> plotly::ggplotly()
plot
#   plotly::ggplotly()
```

### Kataegis events {data-padding=25}

```{r mutsigs_kataegis, echo = F, eval = pcg_report$content$kataegis$eval}

df <- data.frame('sample_id' = character(), 'chrom' = character(), 'start' = integer(), 'end' = integer(),
                 'chrom.arm' = character(), 'length' = integer(), 'number.mut' = integer(), 'weight.C>X' = numeric(),
                 'confidence' = integer(), stringsAsFactors = F)

if(is.data.frame(pcg_report$content$kataegis$events)){
  df <- pcg_report$content$kataegis$events
}
## data frame with potential kataegis events present in tumor sample
myOptions <- list(paging = F,pageLength=5, searching=F,caching=F,
                  buttons = c('csv','excel'),dom = 'Bfrtip')
DT::datatable(df ,options = myOptions,extensions=c("Buttons","Responsive"))

``` 
   
