
sCNA oncogene {.hidden}
===================================== 

Row
-------------------------------------

### Key findings


```{r cna_vbox_mainhits}
flexdashboard::valueBox("sCNA", caption = NULL, color = "#000000", icon = NULL)
```

### Proto-oncogenes subject to amplification

```{r cna_gains_oncogenes, echo = F}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_oncogene_gain,
  color = ifelse(
    pcg_report$content$cna$vstats$n_oncogene_gain > 0,
    pcg_report$settings$conf$report_color,
    pcgrr::color_palette$none),
  icon = "fa-dna", href="#scna-oncogene")
```

### Loss of tumor suppressor genes

```{r cna_loss_tsgene, echo = F}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_tsg_loss,
  color = ifelse(
    pcg_report$content$cna$vstats$n_tsg_loss > 0,
    pcg_report$settings$conf$report_color,
    pcgrr::color_palette$none),
  icon = "fa-dna", href="#scna-tsgene")
```

### Other drug targets subject to amplification

```{r cna_gain_target, echo = F}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_other_drugtarget_gain,
  color = ifelse(
    pcg_report$content$cna$vstats$n_other_drugtarget_gain > 0,
  pcg_report$settings$conf$report_color,
  pcgrr::color_palette$none),
icon = "fa-dna", href="#scna-other")
```

Row
-----------------------------------------------------

### Gain of proto-oncogenes - filters {data-padding=15 data-width=300}


<br><br>

```{r table_browse_scna_oncogene, echo=F, results = "asis", eval = pcg_report$content$cna$vstats$n_oncogene_gain > 0}

cat('\nProto-oncogenes subject to amplifications (right panel) can be filtered according to various criteria:\n')

drug_levels <- levels(as.factor(
  pcg_report[["content"]][["cna"]][["callset"]][["variant_display"]]$TARGETED_INHIBITORS))

oncogene_gain_variants <- 
  dplyr::filter(
    pcg_report[["content"]][["cna"]][["callset"]][["variant_display"]],
    !is.na(.data$TIER) & 
    .data$TIER == 3 & 
      .data$ONCOGENE == TRUE & 
      .data$VARIANT_CLASS == "gain") |>
  dplyr::select(
    dplyr::any_of(
      pcgrr::dt_display$cna_other
    )
  )

oncogene_gain_variants_sd <- 
  crosstalk::SharedData$new(oncogene_gain_variants)

crosstalk::bscols(
  list(
    crosstalk::filter_slider(
      "N_MAJOR", "Major copy number", oncogene_gain_variants_sd, ~N_MAJOR),
    crosstalk::filter_slider(
      "N_MINOR", "Minor copy number", oncogene_gain_variants_sd, ~N_MINOR)
  ),
  list(
    crosstalk::filter_select(
      "SYMBOL", "Gene", oncogene_gain_variants_sd, ~SYMBOL),
    crosstalk::filter_select(
      "EVENT_TYPE", "CNA event", oncogene_gain_variants_sd, ~EVENT_TYPE)
  )
)

```


```{r oncogene_missing_filters, echo=F, results = 'asis', eval = pcg_report$content$cna$vstats$n_oncogene_gain == 0}
cat('\n*  <i> <b>No</b> proto-oncogenes subject to copy number amplifications.</i>',sep='\n')
cat('\n')
```


### Gain of proto-oncogenes {data-padding=15}

<br><br>

```{r table_scna_oncogene, eval = pcg_report$content$cna$vstats$n_oncogene_gain > 0}

dt <- oncogene_gain_variants_sd |>
  DT::datatable(
    escape = F, 
    extensions = c("Buttons","Responsive"), 
    options = list(
      pageLength = 8, 
      scrollY = scrollY_flexdb_container, 
      buttons = c('csv','excel'), 
      scrollX = "900px",
      dom = 'Bfrtip'))

if(length(drug_levels) > 0){
  dt <- dt |>
    DT::formatStyle(
      "TARGETED_INHIBITORS_ALL",
      "TARGETED_INHIBITORS_ALL",
      color = "white", 
      fontWeight = "bold",
      backgroundColor = DT::styleEqual(
        drug_levels, rep(
          "black", 
          length(drug_levels)))
    )
}
dt |>
  DT::formatStyle(
    "SYMBOL",
    "TISSUE_ASSOC_RANK", 
    color = "white", 
    backgroundColor = DT::styleInterval(
      pcgrr::color_palette$cancer_assoc$breaks,
      pcgrr::color_palette$cancer_assoc$values))

```


```{r oncogene_missing_data, echo=F, results = 'asis', eval = pcg_report$content$cna$vstats$n_oncogene_gain == 0}
cat('\n*  <i> <b>No</b> proto-oncogenes subject to copy number amplifications.</i>',sep='\n')
cat('\n')
```

