Tier 1 {data-navmenu="sCNA"}
==================================================================

Row
-------------------------------------

### sCNA

```{r fig.width = 5}
flexdashboard::valueBox("TIER 1", caption = NULL, color = '#000000', icon = NULL)
```

### Biomarker genes

```{r}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_genes_tier1, 
  color = 
    pcg_report$settings$conf$report_color, icon = "fa-dna")

```

### Diagnostic evidence items

```{r}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_eitems_diagnostic_tier1, 
  color = ifelse(
    pcg_report$content$cna$vstats$n_eitems_diagnostic_tier1 > 0,
    pcgrr::color_palette$success,
    pcgrr::color_palette$none), icon = "fa-file-prescription")
```

### Prognostic evidence items

```{r}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_eitems_prognostic_tier1, 
  color = ifelse(
    pcg_report$content$cna$vstats$n_eitems_prognostic_tier1 > 0,
    pcgrr::color_palette$success,
    pcgrr::color_palette$none), icon = "fa-file-prescription")
```

### Predictive evidence items

```{r}
flexdashboard::valueBox(
  pcg_report$content$cna$vstats$n_eitems_predictive_tier1, 
  color = ifelse(
    pcg_report$content$cna$vstats$n_eitems_predictive_tier1 > 0,
    pcgrr::color_palette$success,
    pcgrr::color_palette$none), icon = "fa-file-prescription")
```

Row
-----------------------------------------------------

### Tier 1 variant evidence items - filters {data-padding=15 data-width=300}


<br><br>

```{r table_browse_scna_tier1, echo=F, results = "asis", eval = pcg_report$content$cna$vstats$n_tier1 > 0}

cat('\nEvidence items associated with variants in tier 1 (right panel) can be filtered according to various criteria:\n')

var_eitems_tier1 <- pcg_report$content$cna$callset$variant_display |>
  dplyr::filter(!is.na(.data$TIER) & .data$TIER == 1) |>
  dplyr::select(-c("TIER_DESCRIPTION","TIER_FRAMEWORK")) |>
  dplyr::inner_join(
    pcg_report$content$cna$callset$biomarker_evidence$items,
    by = c("VAR_ID","TIER","VARIANT_CLASS","ENTREZGENE")
  ) |>
  dplyr::distinct() |>
  dplyr::select(
    dplyr::any_of(
      pcgrr::dt_display$cna_eitem))

cna_tier1_shared <- crosstalk::SharedData$new(var_eitems_tier1)
crosstalk::bscols(
  list(
     crosstalk::filter_select(
      "VARIANT_CLASS", "Aberration type", 
      cna_tier1_shared, ~VARIANT_CLASS),
    crosstalk::filter_select(
      "BM_CANCER_TYPE", "Cancer type", 
      cna_tier1_shared, ~BM_CANCER_TYPE),
    crosstalk::filter_select(
      "BM_CLINICAL_SIGNIFICANCE", "Clinical significance", 
      cna_tier1_shared, ~BM_CLINICAL_SIGNIFICANCE),
    crosstalk::filter_slider(
      "BM_RATING", "Rating", cna_tier1_shared, 
      ~BM_RATING, min = 0, max = 5, step = 1, ticks = T)

  ),
  list(
    crosstalk::filter_select(
      "BM_EVIDENCE_TYPE", "Evidence type", 
      cna_tier1_shared, ~BM_EVIDENCE_TYPE),
    crosstalk::filter_select(
      "BM_EVIDENCE_LEVEL", "Evidence level", 
      cna_tier1_shared, ~BM_EVIDENCE_LEVEL),
    crosstalk::filter_select(
      "BM_EVIDENCE_DIRECTION", "Evidence direction", 
      cna_tier1_shared, ~BM_EVIDENCE_DIRECTION),
    crosstalk::filter_select(
      "BM_THERAPEUTIC_CONTEXT", "Therapeutic context", 
      cna_tier1_shared, ~BM_THERAPEUTIC_CONTEXT)
  )
)


```


```{r tier1_scna_missing_filters, echo=F, results = 'asis', eval = pcg_report$content$cna$vstats$n_tier1 == 0}
cat('\n*  <i> <font style="font-size: 110%"><b>No</b> somatic copy-number aberrations of strong clinical significance found.</font></i>', sep = '\n')
cat('\n')
```


### Tier 1 - variant evidence items {data-padding=15}

<br><br>


```{r table_scna_tier1, eval = pcg_report$content$cna$vstats$n_tier1 > 0}

cna_tier1_shared |>
  DT::datatable(
    escape = F, 
    extensions = c("Buttons","Responsive"), 
    options = list(
      buttons = c('csv','excel'), 
      scrollCollapse=T, 
      scrollY = scrollY_flexdb_container,
      fixedColumns = T,
      fixedHeader = T,
      scrollX = "900px",
      columnDefs = list(
        list(
          width = '90px', targets = c(1,2,3,4,5,6))),
      dom = 'Bfrtip')) |>
  DT::formatStyle(
    'BM_EVIDENCE_LEVEL', 
    backgroundColor = DT::styleEqual(
      pcgrr::color_palette$clinical_evidence$levels,
      pcgrr::color_palette$clinical_evidence$values))

```


```{r tier1_scna_missing_data, echo=F, results = 'asis', eval = pcg_report$content$cna$vstats$n_tier1 == 0}
cat('\n*  <i> <font style="font-size: 110%"><b>No</b> somatic copy-number aberrations of strong clinical significance found.</font></i>',sep='\n')
cat('\n')
```

