### Raw mutational spectrum

As a background perspective, we here provide various views of the raw mutational spectrum for the sample, i.e. not considering a signature re-fitting analysis.

::: {.panel-tabset .nav-pills}

#### SBS - mutational contexts

<br>

```{r setup_spectra_data}
#| echo: false
#| eval: true

msig_content <- 
  pcg_report$content$mutational_signatures
```

```{r raw_context_plot}
#| output: asis
#| eval: !expr is.null(msig_content$result$mut_mat) == FALSE

catalogue_mat <- 
  msig_content$result$mut_mat

y_max <- 
  plyr::round_any(
    max(catalogue_mat[,1] / sum(catalogue_mat[,1])),
    0.05, f = ceiling)

plotly::ggplotly(
  height = 400,
  MutationalPatterns::plot_96_profile(
    catalogue_mat,
    colors = head(pcgrr::color_palette$tier$values, 6),
    ymax = y_max)
)

```


```{r missing_context_plot}
#| output: asis
#| eval: !expr is.null(msig_content$result$mut_mat) == TRUE

cat("\n::: {.callout-warning}\n## No SNVs\n\nNo SNVs/single base substitutions", 
    "were found in this sample\n\n:::\n\n")

```


#### SBS - type occurrences

<br>

```{r sbs_type_occurrences}
#| eval: !expr is.null(msig_content$result$type_occurrences) == FALSE
#| output: asis


if(rowSums(msig_content$result$type_occurrences[1:6]) > 0){
  plotly::ggplotly(
    height = 400,
    MutationalPatterns::plot_spectrum(
      msig_content$result$type_occurrences, 
      CT = TRUE,
      error_bars = 'none',
      colors = head(
        pcgrr::color_palette$tier$values, 7))) |>
    plotly::layout(
      legend = list(
        orientation = "h",         # horizontal legend
        x = 0.5,                   # center it
        xanchor = "center",        # anchor it at the center
        y = -0.2                   # place it below the plot
      )
    )
}

```

```{r sbs_types_missing}
#| eval: !expr (is.null(msig_content$result$type_occurrences) == TRUE) & pcg_report$content$snv_indel$vstats$n_snv == 0
#| output: asis

cat("\n::: {.callout-warning}\n## No SNVs\n\nNo SNVs/single base substitutions", 
    "were found in this sample\n\n:::\n\n")

```


#### ID - mutational contexts

<br>

```{r indel_contexts}
#| eval: !expr is.null(msig_content$result$indel_counts) == FALSE
#| fig-width: 14
#| fig-height: 7

MutationalPatterns::plot_indel_contexts(
  counts = msig_content$result$indel_counts, 
  condensed = T) + 
  ggplot2::theme(legend.position = "bottom") + 
  ggplot2::theme(text = ggplot2::element_text(size = 14))


```

```{r indel_contexts_missing}
#| eval: !expr is.null(msig_content$result$indel_counts) == TRUE
#| output: asis

cat(
  "\n::: {.callout-warning}\n## No/very few InDels\n\nNo/very few insertion/deletions",
  "were analyzed in this sample\n\n:::\n")

```

:::
