#!/usr/bin/env python

import csv
import re
import argparse
import os
import subprocess
import logging
import sys
import pcgrutils
import pandas as np
import cyvcf
from cyvcf2 import VCF

def __main__():
   
   parser = argparse.ArgumentParser(description='Verify input data for PCGR')
   parser.add_argument('pcgr_dir',help='Docker location of PCGR base directory with accompanying data directory, e.g. /data')
   parser.add_argument('input_vcf', help='VCF input file with somatic query variants (SNVs/InDels)')
   parser.add_argument('input_cna', help='Somatic copy number query segments (tab-separated values)')
   parser.add_argument('tumor_dp_tag', help='')
   parser.add_argument('tumor_af_tag', help='')
   parser.add_argument('normal_dp_tag', help='')
   parser.add_argument('normal_af_tag', help='')
   parser.add_argument('call_conf_tag', help='')
   args = parser.parse_args()
   
   ret = verify_pcgr_input(args.pcgr_dir, args.input_vcf, args.input_cna, args.tumor_dp_tag, args.tumor_af_tag, args.normal_dp_tag, args.normal_af_tag, args.call_conf_tag)
   if ret != 0:
      sys.exit(-1)

def pcgr_error_message(message):
   logger.error('')
   logger.error(message)
   logger.error('')
   return -1

def is_valid_cna_segment_file(cna_segment_file, logger):
   """
   Function that checks whether the CNA segment file adheres to the correct format
   """
   cna_reader = csv.DictReader(open(cna_segment_file,'r'), delimiter='\t')
   ## check that required columns are present
   if not ('Chromosome' in cna_reader.fieldnames and 'Segment_Mean' in cna_reader.fieldnames and 'Start' in cna_reader.fieldnames and 'End' in cna_reader.fieldnames): 
      err_msg = "Copy number segment file (" + str(cna_segment_file) + ") is missing required column(s): 'Chromosome', 'Start', 'End', or  'Segment_Mean'\n. Column names present in file: " + str(cna_reader.fieldnames)
      return pcgr_error_message(err_msg)
   
   cna_dataframe = np.read_csv(cna_segment_file, sep="\t")
   if not cna_dataframe['Start'].dtype.kind in 'i': ## check that 'Start' is of type integer
      err_msg = '\'Start\' column of copy number segment file contains non-integer values'
      return pcgr_error_message(err_msg)
   if not cna_dataframe['End'].dtype.kind in 'i': ## check that 'End' is of type integer
      err_msg = '\'End\' column of copy number segment file contains non-integer values'
      return pcgr_error_message(err_msg)

   if not cna_dataframe['Segment_Mean'].dtype.kind in 'if': ## check that 'Segment_Mean' is of type integer/float
      err_msg = '\'Segment_Mean\' column of copy number segment file contains non-numerical values'
      return pcgr_error_message(err_msg)

   for rec in cna_reader:
      if int(rec['End']) < int(rec['Start']): ## check that 'End' is always greather than 'Start'
         err_msg = 'Detected wrongly formatted chromosomal segment - \'Start\' is greater than \'End\' (' + str(rec['Chromosome']) + ':' + str(rec['Start']) + '-' + str(rec['End']) + ')'
         return pcgr_error_message(err_msg)
      if rec['End'] < 1 or rec['Start'] < 1: ## check that 'Start' and 'End' is always non-negative
         err_msg = 'Detected wrongly formatted chromosomal segment - \'Start\' or \'End\' is less than or equal to zero (' + str(rec['Chromosome']) + ':' + str(rec['Start']) + '-' + str(rec['End']) + ')'
         return pcgr_error_message(err_msg)
   logger.info('Copy number segment file (' + str(cna_segment_file) + ') adheres to the correct format')
   return 0

def is_valid_vcf(vcf_validator_output_file):
   """
   Function that reads the output file of EBIvariation/vcf-validator and reports potential errors and validation status 
   """
   valid_vcf = -1
   ret = {}
   if os.path.exists(vcf_validator_output_file):
      f = open(vcf_validator_output_file,'r')
      error_messages = []
      for line in f:
         if not re.search(r' \(warning\)$|^Reading from ',line.rstrip()): ## ignore warnings
            if line.startswith('Line '):
               error_messages.append(line.rstrip())
            if line.endswith('the input file is valid'): ## valid VCF
               valid_vcf = 1
            if line.endswith('the input file is not valid'):  ## non-valid VCF
               valid_vcf = 0
      f.close()
      os.system('rm -f ' + str(vcf_validator_output_file))
      ret['error_messages'] = error_messages
      ret['validation_status'] = valid_vcf
   return ret


def check_existing_vcf_info_tags(input_vcf, pcgr_directory, logger):
   
   """
   Function that compares the INFO tags in the query VCF and the INFO tags generated by PCGR
   If any coinciding tags, an error will be returned
   """
   
   vep_infotags_desc = pcgrutils.read_infotag_file(os.path.join(pcgr_directory,'data','vep_infotags.tsv'))
   pcgr_infotags_desc = pcgrutils.read_infotag_file(os.path.join(pcgr_directory,'data','pcgr_infotags.tsv'))

   vcfanno_tags = {}
   for db in ['intogen_driver_mut','dbsnp','oneKG','docm','exac','gnomad','civic','cbmdb','dbnsfp','clinvar','icgc','cosmic']:
      vcfanno_tag_file = os.path.join(pcgr_directory,'data',str(db),str(db) + '.vcfanno.vcf_info_tags.txt')
      try:
         f = open(vcfanno_tag_file, 'r')
         for line in f:
            if line.startswith('##INFO'):
               tag = re.sub(r'##INFO=<ID=','',str(line.rstrip().split(',')[0]))
               vcfanno_tags[tag] = 1
      except IOError:
         logger.error('File ' + str(vcfanno_tag_file) + ' does not exist')
         
   vcf_reader = cyvcf.Reader(open(input_vcf, 'r'))
   logger.info('Checking if existing INFO tags of query VCF file coincide with PCGR INFO tags')
   ret = 1
   for k in vcf_reader.infos.keys():
      if k in vep_infotags_desc.keys() or k in pcgr_infotags_desc.keys() or k in vcfanno_tags.keys() or k == 'EFFECT_PREDICTIONS':
         logger.error('INFO tag ' + str(k) + ' in the query VCF coincides with a VCF annotation tag produced by PCGR - please remove or rename this tag in your query VCF')
         ret = -1
   return ret


def check_ad_dp_tags(vcf, tumor_dp_tag, tumor_af_tag, normal_dp_tag, normal_af_tag, call_conf_tag, logger):
   
   found_taf_tag = 0
   found_tdp_tag = 0
   found_naf_tag = 0
   found_ndp_tag = 0
   found_call_conf_tag = 0
   
   for e in vcf.header_iter():
      header_element = e.info()
      if 'ID' in header_element.keys() and 'HeaderType' in header_element.keys():
         if header_element['HeaderType'] == 'INFO':
            if header_element['ID'] == tumor_dp_tag:
               if header_element['Type'] == 'Integer':
                  logger.info('Found tag for tumor variant sequencing depth (--tumor_dp_tag ' + str(tumor_dp_tag) + ') in input VCF')
                  found_tdp_tag = 1
               else:
                  err_msg = 'Tag for tumor variant sequencing depth (--tumor_dp_tag ' + str(tumor_dp_tag) + ') is not correctly specified in input VCF (Type=' + str(header_element['Type']) + '), should be Type=Integer'
                  pcgr_error_message(err_msg)
            if header_element['ID'] == tumor_af_tag:
               if header_element['Type'] == 'Float':
                  logger.info('Found tag for tumor variant allelic fraction (--tumor_af_tag ' + str(tumor_af_tag) + ') in input VCF')
                  found_taf_tag = 1
               else:
                  err_msg = 'Tag for tumor variant allelic fraction (--tumor_af_tag ' + str(tumor_af_tag) + ') is not correctly specified in input VCF (Type=' + str(header_element['Type']) + '), should be Type=Float'
                  pcgr_error_message(err_msg)
            if header_element['ID'] == normal_dp_tag:
               if header_element['Type'] == 'Integer':
                  logger.info('Found tag for normal/control variant sequencing depth (--normal_dp_tag ' + str(normal_dp_tag) + ') in input VCF')
                  found_ndp_tag = 1
               else:
                  err_msg = 'Tag for normal/control variant sequencing depth (--normal_dp_tag ' + str(normal_dp_tag) + ') is not correctly specified in input VCF (Type=' + str(header_element['Type']) + '), should be Type=Integer'
                  pcgr_error_message(err_msg)
            if header_element['ID'] == normal_af_tag:
               if header_element['Type'] == 'Float':
                  logger.info('Found tag for normal/control allelic fraction (--normal_af_tag ' + str(normal_af_tag) + ') in input VCF')
                  found_naf_tag = 1
               else:
                  err_msg = 'Tag for for normal/control allelic fraction (--normal_af_tag ' + str(normal_af_tag) + ') is not correctly specified in input VCF (Type=' + str(header_element['Type']) + ') should be Type=Float'
                  pcgr_error_message(err_msg)
            if header_element['ID'] == call_conf_tag:
               if header_element['Type'] == 'String':
                  logger.info('Found tag for variant call confidence (--call_conf_tag ' + str(call_conf_tag) + ') in input VCF')
                  found_call_conf_tag = 1
               else:
                  err_msg = 'Tag for variant call confidence (--call_conf_tag) is not correctly specified in input VCF (Type=' + str(header_element['Type']) + '), should be Type=String'
                  pcgr_error_message(err_msg)
   
   
   if call_conf_tag != '_na' and found_call_conf_tag == 0:
      logger.warn('Could not find the specified --call_conf_tag (' + str(call_conf_tag) + ') in input VCF')
   if tumor_dp_tag != '_na' and found_tdp_tag == 0:
      logger.warn('Could not find the specified --tumor_dp_tag (' + str(tumor_dp_tag) + ') in input VCF')
   if tumor_af_tag != '_na' and found_taf_tag == 0:
      logger.warn('Could not find the specified --tumor_af_tag (' + str(tumor_af_tag) + ') in input VCF')
   if normal_dp_tag != '_na' and found_ndp_tag == 0:
      logger.warn('Could not find the specified --normal_dp_tag (' + str(normal_dp_tag) + ') in input VCF')
   if normal_af_tag != '_na' and found_naf_tag == 0:
      logger.warn('Could not find the specified --normal_af_tag (' + str(normal_af_tag) + ') in input VCF')
   
   if found_tdp_tag == 1 and found_taf_tag == 0:
      logger.warn('BOTH \'--tumor_dp_tag\' AND \'--tumor_af_tag\' need to be specified for use in tumor report (\'--tumor_af_tag\' is missing)')
   
   if found_tdp_tag == 0 and found_taf_tag == 1:
      logger.warn('BOTH \'--tumor_dp_tag\' AND \'--tumor_af_tag\' need to be specified for use in tumor report (\'--tumor_dp_tag\' is missing)')
   
   if found_ndp_tag == 1 and found_naf_tag == 0:
      logger.warn('BOTH \'--normal_dp_tag\' AND \'--normal_af_tag\' need to be specified for use in tumor report (\'--normal_af_tag\' is missing)')
   
   if found_ndp_tag == 0 and found_naf_tag == 1:
      logger.warn('BOTH \'--normal_dp_tag\' AND \'--normal_af_tag\' need to be specified for use in tumor report (\'--normal_dp_tag\' is missing)')
         

   return 0

def verify_pcgr_input(pcgr_directory, input_vcf, input_cna, tumor_dp_tag, tumor_af_tag, normal_dp_tag, normal_af_tag, call_conf_tag):
   """
   Function that reads the input files to PCGR (VCF file and Tab-separated values file with copy number segments) and performs the following checks:
   1. Check that VCF file is properly formatted (according to EBIvariation/vcf-validator - VCF v4.2)
   2. Check that no INFO annotation tags in the query VCF coincides with those generated by PCGR
   3. Check that provided columns for tumor/normal coverage and allelic depths are found in VCF
   4. Check that if VCF have variants with multiple alternative alleles (e.g. 'A,T') run vt decompose
   5. Check that copy number segment file has required columns and correct data types (and range)
   6. Any genotype data from VCF input file is stripped, and the resulting VCF file is sorted and indexed (bgzip + tabix) 
   """
   logger = pcgrutils.getlogger('pcgr-check-input')
   input_vcf_pcgr_ready = '/workdir/output/' + re.sub(r'(\.vcf$|\.vcf\.gz$)','.pcgr_ready.tmp.vcf',os.path.basename(input_vcf))
   input_vcf_pcgr_ready_decomposed = '/workdir/output/' + re.sub(r'(\.vcf$|\.vcf\.gz$)','.pcgr_ready.vcf',os.path.basename(input_vcf))
   
   if not input_vcf == 'None':
      logger.info('Validating VCF file with EBIvariation/vcf-validator')
      vcf_validation_output_file = '/workdir/output/' + re.sub(r'(\.vcf$|\.vcf\.gz$)','.vcf_validator_output',os.path.basename(input_vcf))
      command_v42 = 'vcf_validator --input ' + str(input_vcf) + ' --version v4.2 > ' + str(vcf_validation_output_file)
      if input_vcf.endswith('.gz'):
         command_v42 = 'bgzip -dc ' + str(input_vcf) + ' | vcf_validator --version v4.2 > ' + str(vcf_validation_output_file)
      
      os.system(command_v42)
      validation_results = is_valid_vcf(vcf_validation_output_file)
      
      if not validation_results['validation_status']:
         error_string_42 = '\n'.join(validation_results['error_messages'])
         validation_status = 'VCF file is NOT valid according to v4.2 specification'
         logger.error(validation_status + ':\n' + str(error_string_42))
         return -1
      else:
         validation_status = 'VCF file ' + str(input_vcf) + ' is valid according to v4.2 specification'
         logger.info(validation_status)
      
      tag_check = check_existing_vcf_info_tags(input_vcf, pcgr_directory, logger)
      if tag_check == -1:
         return -1
      else:
         logger.info('No query VCF INFO tags coincide with PCGR INFO tags')
      
      if validation_results['validation_status']:
         multiallelic_alt = 0
         vcf = VCF(input_vcf)
         check_ad_dp_tags(vcf, tumor_dp_tag, tumor_af_tag, normal_dp_tag, normal_af_tag, call_conf_tag, logger)
         for rec in vcf:
            POS = rec.start + 1
            alt = ",".join(str(n) for n in rec.ALT)
            if len(rec.ALT) > 1:
               logger.warning("Multiallelic site detected:" + str(rec.CHROM) + '\t' + str(POS) + '\t' + str(rec.REF) + '\t' + str(alt))
               multiallelic_alt = 1
         command_vcf_sample_free1 = 'egrep \'^##\' ' + str(input_vcf) + ' > ' + str(input_vcf_pcgr_ready)
         command_vcf_sample_free2 = 'egrep \'^#CHROM\' ' + str(input_vcf) + ' | cut -f1-8 >> ' + str(input_vcf_pcgr_ready)
         command_vcf_sample_free3 = 'egrep -v \'^#\' ' + str(input_vcf) + ' | sed \'s/^chr//\' | cut -f1-8 | egrep \'^[0-9]\' | sort -k1,1n -k2,2n -k3,3 -k4,4 >> ' + str(input_vcf_pcgr_ready)
         command_vcf_sample_free4 = 'egrep -v \'^#\' ' + str(input_vcf) + ' | sed \'s/^chr//\' | cut -f1-8 | egrep -v \'^[0-9]\' | egrep \'^[XYM]\' | sort -k1,1 -k2,2n -k3,3 -k4,4 >> ' + str(input_vcf_pcgr_ready)
         command_vcf_sample_free5 = 'egrep -v \'^#\' ' + str(input_vcf) + ' | sed \'s/^chr//\' | cut -f1-8 | egrep -v \'^[0-9]\' | egrep -v \'^[XYM]\' | sort -k1,1 -k2,2n -k3,3 -k4,4 >> ' + str(input_vcf_pcgr_ready)
         if input_vcf.endswith('.gz'):
            command_vcf_sample_free1 = 'bgzip -dc ' + str(input_vcf) + ' | egrep \'^##\' > ' + str(input_vcf_pcgr_ready)
            command_vcf_sample_free2 = 'bgzip -dc ' + str(input_vcf) + ' | egrep \'^#CHROM\' | cut -f1-8 >> ' + str(input_vcf_pcgr_ready)
            command_vcf_sample_free3 = 'bgzip -dc ' + str(input_vcf) + ' | egrep -v \'^#\' | sed \'s/^chr//\' | cut -f1-8 | egrep \'^[0-9]\' | sort -k1,1n -k2,2n -k3,3 -k4,4 >> ' + str(input_vcf_pcgr_ready)
            command_vcf_sample_free4 = 'bgzip -dc ' + str(input_vcf) + ' | egrep -v \'^#\' | sed \'s/^chr//\' | cut -f1-8 | egrep -v \'^[0-9]\' | egrep \'^[XYM]\' | sort -k1,1 -k2,2n -k3,3 -k4,4 >> ' + str(input_vcf_pcgr_ready)
            command_vcf_sample_free5 = 'bgzip -dc ' + str(input_vcf) + ' | egrep -v \'^#\' | sed \'s/^chr//\' | cut -f1-8 | egrep -v \'^[0-9]\' | egrep -v \'^[XYM]\' | sort -k1,1 -k2,2n -k3,3 -k4,4 >> ' + str(input_vcf_pcgr_ready)
         
         os.system(command_vcf_sample_free1)
         os.system(command_vcf_sample_free2)
         os.system(command_vcf_sample_free3)
         os.system(command_vcf_sample_free4)
         os.system(command_vcf_sample_free5)

         if multiallelic_alt == 1:
            logger.info('Decomposing multi-allelic sites in input VCF file using \'vt decompose\'')
            command_decompose = 'vt decompose -s ' + str(input_vcf_pcgr_ready) + ' > ' + str(input_vcf_pcgr_ready_decomposed) + ' 2> /workdir/output/decompose.log'
            os.system(command_decompose)
         else:
            command_copy = 'cp ' + str(input_vcf_pcgr_ready) + ' ' + str(input_vcf_pcgr_ready_decomposed)
            os.system(command_copy)
         os.system('bgzip -f ' + str(input_vcf_pcgr_ready_decomposed))
         os.system('tabix -p vcf ' + str(input_vcf_pcgr_ready_decomposed) + '.gz')
         os.system('rm -f ' + str(input_vcf_pcgr_ready) + ' /workdir/output/decompose.log')
      
   if not input_cna == 'None':
      ret = is_valid_cna_segment_file(input_cna, logger)
      return ret
   
   return 0
   
if __name__=="__main__": __main__()

