name: deploy

on:
  push:
    branches:
      - main
      - dev

env:
  conda_token: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  conda_recipe: conda/recipe
  conda_env_yaml: conda/env/yaml
  conda_env_lock: conda/env/lock
  conda_org: pcgr
  VERSION: '2.2.5.9003' # bump
jobs:
  build_conda_pkgs:
    # When merging to one of the branches above and the commit message matches
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build ${{ matrix.pkg }} conda pkg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [pcgr, pcgrr]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 🚚 Code checkout
        uses: actions/checkout@v6
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: ${{ env.conda_env_yaml }}/condabuild.yaml
          activate-environment: condabuild_env
          miniforge-version: latest
      - name: 🐍🔧 Conda pkg build
        run: |
          DEV_CHANNEL=""
          [[ "${{ github.ref }}" == "refs/heads/dev" ]] && DEV_CHANNEL="--channel ${{ env.conda_org }}/label/dev"
          rattler-build build \
            --recipe-dir ${{ env.conda_recipe }}/${{ matrix.pkg }} \
            ${DEV_CHANNEL} \
            --channel ${{ env.conda_org }} \
            --channel bioconda \
            --channel conda-forge \
            --channel-priority flexible \
            --output-dir ${RUNNER_TEMP}/out_${{ matrix.pkg }}
      - name: 🐍🪁 Conda pkg upload
        run: |
          pkg_path=$(find ${RUNNER_TEMP}/out_${{ matrix.pkg }} -type f -name "*.conda")
          LABEL_ARG=""
          [[ "${{ github.ref }}" == "refs/heads/dev" ]] && LABEL_ARG="--channel dev"
          rattler-build upload anaconda \
            --owner ${{ env.conda_org }} \
            --api-key ${{ env.conda_token }} \
            ${LABEL_ARG} \
            ${pkg_path}

  conda_lock:
    name: 🔒 Conda lock
    runs-on: ubuntu-latest
    needs: [build_conda_pkgs]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 🚚 Code checkout
        uses: actions/checkout@v6
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ${{ env.conda_env_yaml }}/condabuild.yaml
          activate-environment: condabuild_env
          auto-update-conda: true
          miniforge-version: latest
      - name: 🔒 Conda lock
        run: |
          # handle dev branch with dev label channel
          CHANNEL_ARGS="--channel ${{ env.conda_org }} --channel bioconda --channel conda-forge"
          [[ "${{ github.ref }}" == "refs/heads/dev" ]] && CHANNEL_ARGS="--channel ${{ env.conda_org }}/label/dev ${CHANNEL_ARGS}"
          for pkg in pcgr pcgrr; do
            conda-lock lock -f ${{ env.conda_env_yaml }}/${pkg}.yaml --lockfile lock-${pkg}.yaml ${CHANNEL_ARGS} -p linux-64
            conda-lock render -p linux-64 lock-${pkg}.yaml --filename-template "${pkg}-{platform}.lock" \
              && rm lock-${pkg}.yaml \
              && mv ${pkg}-linux-64.lock ${{ env.conda_env_lock }}/
          done

      - name: 💾 Commit lockfiles
        run: |
          git status
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          MSG="[bot] Updating conda-lock files (v${{ env.VERSION }})"
          git add ${{ env.conda_env_lock }}/
          git commit -m "${MSG}"
          git push
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: ${{ env.conda_env_yaml }}/pkgdown.yaml
          activate-environment: pkgdown_env
          miniforge-version: latest
      - name: 🌐 Website publish
        run: |
          cp pcgrr/DESCRIPTION . # hack for pkgdown to work
          printf "pcgrr version:\n"
          Rscript -e "packageVersion('pcgrr')"
          Rscript -e "pkgdown::deploy_to_branch(pkg = 'pcgrr', commit_message = 'Built PCGR website: https://sigven.github.io/pcgr/', branch = 'gh-pages', new_process = FALSE)"

  docker_deploy:
    name: Build and deploy Docker
    runs-on: ubuntu-latest
    needs: conda_lock
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 🚚 Code checkout
        uses: actions/checkout@v6
      - id: pull_lock_commit
        name: 📥 Pull lock commit
        run: |
            git pull --no-rebase # for pulling in the changed locks
            git --no-pager log --decorate=short --pretty=oneline -n3
            LATEST_COMMIT_HASH="$(git --no-pager log -1 --format='%H')"
            echo "latest_commit_hash=${LATEST_COMMIT_HASH}" >> $GITHUB_OUTPUT
      - name: 🔖 Tag creation
        uses: actions/github-script@v8
        env:
          LATEST_COMMIT_HASH: ${{ steps.pull_lock_commit.outputs.latest_commit_hash }}
        with:
          script: |
            const the_tag_name = 'refs/tags/v' + process.env.VERSION
            const the_sha = process.env.LATEST_COMMIT_HASH
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: the_tag_name,
              sha: the_sha
            })

      - name: 🗑 Free Disk Space
        uses: jlumbroso/free-disk-space@v1
      # work with tag from above
      - name: 🚚 Code checkout
        uses: actions/checkout@v6
        with:
          ref: v${{ env.VERSION }}
      - name: 🏰 QEMU setup
        uses: docker/setup-qemu-action@v4
      - name: 🏯 Buildx setup
        uses: docker/setup-buildx-action@v4
      - name: 🐙 GitHub CR login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # use the outputs=docker with dest to directly save to tar for apptainer
      - name: 🐳 Docker img build, tar and push to GHCR
        uses: docker/build-push-action@v7
        with:
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          outputs: type=docker,dest=pcgr_${{ env.VERSION }}.tar
          context: .
          push: true
          platforms: linux/amd64

      # Apptainer
      - name: Apptainer setup
        uses: eWaterCycle/setup-apptainer@v2
      - name: 🕹️ Apptainer build
        run: |
          ls -lSha
          df -h
          echo "Building Apptainer SIF"
          echo "---------------------------------"
          apptainer build pcgr_singularity_${{ env.VERSION }}.sif docker-archive://pcgr_${{ env.VERSION }}.tar
          echo "---------------------------------"
          ls -lSha
      - name: Upload SIF to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.actor }} --password-stdin oras://ghcr.io
          apptainer push pcgr_singularity_${{ env.VERSION }}.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${{ env.VERSION }}.singularity
